### PR TITLE
First pass - Content

### PR DESCRIPTION
**Pull request by markbrown4**
Fonts, headings, copy, images, captions, blockquotes, lists, tables, code, syntax highlighting
I tried to make as much of the existing content work well with the new styles

**todos**
- [x] Active states on menu
- [ ] better navigation from Home and posts#show, 'Next article' might be enough
- [ ] consistent branding() / footer content
- [ ] search available on every page
- [ ] better font-sizing on mobile

### CODE REVIEW

**Comment by pat** [comment]
Finally found some time to look over this properly... some thoughts:

* Generally, I really like it! Clean, effective, solid focus on the content but not too bland.
* Need to change that header image though... having the strip of colour across the top works well, but as I mentioned the other day, I want to retire that image.
* Not sure if some spacing between list items on the 'Posts' page would be good? Just feels a little cramped, harder to distinguish each post title separately.
* Certainly open to putting search on every page (maybe in the footer? Granted, traditionally it's at the top of the page, just also don't want too much to get in the way before the proper content starts.)

I'll ponder a better image to stretch across the top - it'll likely be a photo I've taken, similarish to what I've put in place for each event on the Events page... open to other suggestions if any inspiration comes to mind :)

And thanks for the time you've spent on this! Greatly appreciated, and keen to pay you something for your time.

**Comment by markbrown4** [comment]
Something for Railscamp? ;)

**Comment by pat** [comment]
You'll be there? I won't arrive until Sunday, got a wedding on Saturday. But yes, perhaps… I might take a stab at it tonight at the Ruby Hack night too. We shall see…

**Comment by markbrown4** [comment]
Nah, I won't be there.  Was just nudging :)

Yell out if there's anything else I can help with.

On Tue, Jun 9, 2015 at 11:46 AM, Pat Allan <notifications@github.com> wrote:

> You'll be there? I won't arrive until Sunday, got a wedding on Saturday.
> But yes, perhaps… I might take a stab at it tonight at the Ruby Hack night
> too. We shall see…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pat/pat.github.com/pull/12#issuecomment-110193333>.
>



-- 
Regards,

Mark Brown

http://adioso.com/
http://development.inspire9.com/

**Comment by pat** [comment]
Merged (though GitHub doesn't think so), with active nav, different header image, prev/next post links at the bottom of posts.

**Comment by pat** [comment]
- [ ] Probably change the header background colour to something that better fits the photo.
- [ ] Better styling of prev/next post links
- [ ] Fix search JS / form
- [ ] Improve styling of search page
- [ ] Global footer content

**Comment by pat** [comment]
Deployed to freelancing-gods.com. Some colour changes and various tweaks. I'm sure things can be improved further, but wanted to ship it anyway :) :ship:

Many thanks for your help with this!

**Comment by markbrown4** [comment]
Nice.

If you have a higher res image of Melbourne for the header, it will
probably look better full width. Something like

#god {
  height: 100px;
  background: url(/images/bourke.png) no-repeat 50% 50%;
  background-size: cover;
}



On Sun, Jun 28, 2015 at 11:03 PM, Pat Allan <notifications@github.com>
wrote:

> Deployed to freelancing-gods.com. Some colour changes and various tweaks.
> I'm sure things can be improved further, but wanted to ship it anyway :) [image:
> :ship:]
>
> Many thanks for your help with this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pat/pat.github.com/pull/12#issuecomment-116275682>.
>



-- 
Regards,

Mark Brown

http://adioso.com/
http://development.inspire9.com/

**Pull request closed without merging**
